# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title : PseudoLab [MVG-Tutorial]
author: PseudoLab
logo: 'PseudoLab_logo.png'


# Short description about the book
description: >-
  Jupyter book template for PseudoLab MVG-Tutorial study group

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: off

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
# Launch button settings
repository:
  url                         : https://github.com/pseudo-lab/MVG-Tutorial
  path_to_book                : book
  branch: master

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
  
  latex_engine                : "xelatex"
  latex_documents:
    targetname: book.tex
    
html:
  favicon: 'PseudoLab_logo.png'
  use_issues_button: true
  use_repository_button: true
  
sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

# Interact link settings
notebook_interface            : "notebook"